# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FridayUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FRIDAYUI(object):
    def setupUi(self, FRIDAYUI):
        FRIDAYUI.setObjectName("FRIDAYUI")
        FRIDAYUI.resize(894, 576)
        self.centralwidget = QtWidgets.QWidget(FRIDAYUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 901, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/lenovo/Pictures/sFaoXq3.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 480, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 480, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 381, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/lenovo/Pictures/T8bahf.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(590, 10, 141, 41))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(740, 10, 141, 41))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(600, 330, 281, 211))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/lenovo/Pictures/f16054ef24cddf2115e5524df9a54164.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 480, 341, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/lenovo/Pictures/98050d0e5e2ec6a063d514b7600a741c.gif"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 280, 321, 61))
        self.textBrowser_3.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        FRIDAYUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(FRIDAYUI)
        QtCore.QMetaObject.connectSlotsByName(FRIDAYUI)

    def retranslateUi(self, FRIDAYUI):
        _translate = QtCore.QCoreApplication.translate
        FRIDAYUI.setWindowTitle(_translate("FRIDAYUI", "MainWindow"))
        self.pushButton.setText(_translate("FRIDAYUI", "RUN"))
        self.pushButton_2.setText(_translate("FRIDAYUI", "TERMINATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FRIDAYUI = QtWidgets.QMainWindow()
    ui = Ui_FRIDAYUI()
    ui.setupUi(FRIDAYUI)
    FRIDAYUI.show()
    sys.exit(app.exec_())
